export const SECONDS_PER_MINUTE = 60;
export const MS_PER_SECOND = 1_000;
export const MINUTES = SECONDS_PER_MINUTE * MS_PER_SECOND;
export const SESSION_DURATION_MINUTES = 30;
export const SESSION_TTL_MS = SESSION_DURATION_MINUTES * MINUTES;
export const MAX_MESSAGE_LENGTH_CHARS = 4_000;
